import Head from 'next/head'
import GroupRingtone from '../components/GroupRingtone'
import Layout from '../components/Layout'
import Posts from '../components/Posts'
import SearchHeader from '../components/SearchHeader'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ringtonez</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout>
      
      
        <div>
          <SearchHeader />
          <GroupRingtone />
          <Posts />
        </div>
      </Layout>
    </div>
  )
}
