import Head from 'next/head'
import GroupRingtone from '../components/GroupRingtone'
import Layout from '../components/Layout'
import Posts from '../components/Posts'
import SearchHeader from '../components/SearchHeader'
import styles from '../styles/Home.module.css'

export default function Home ({data}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Ringtonez</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout>
      
      
        <div>
          <SearchHeader />


          <GroupRingtone />
          <Posts />
        </div>
      </Layout>
    </div>
  )
}


export async function grtServerSide (){
  const getPosts = await fetch('https://zigtone.com/wp-json/wp/v2/posts');
  const data = await getPosts.json();
  console.log('Data' , data)
  return {props: {data}}

}